spring:
  application:
    name: cpss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cpsss
    username: ${CPSS_USERNAME:default_user}
    password: ${CPSS_PASSWORD:default_pass}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml